[config]
reload_apps = true

[config.wallpaper]
command = "swww"
set = false


[templates.qt5ct]
input_path = "templates/qtct-colors.conf"
output_path = "~/.config/qt5ct/colors/matugen.conf"

[templates.qt6ct]
input_path = "templates/qtct-colors.conf"
output_path = "~/.config/qt6ct/colors/matugen.conf"

[templates.waybar]
input_path = 'templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.obsidian]
input_path = "templates/obsidian.css"
output_path = "~/personal/obsidian/.obsidian/themes/Border/theme.css"

[templates.hyprland]
input_path = 'templates/hyprland.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.pywalfox]
input_path = 'templates/pywallfox.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

[templates.kitty]
input_path = 'templates/kitty.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = "kill -SIGUSR1 $(pidof kitty)"

[templates.wlogout]
input_path = 'templates/wlogout.css'
output_path = '~/.config/wlogout/colors.css'

[templates.rofi]
input_path = 'templates/rofi.rasi'
output_path = '~/.config/rofi/colors.css'
post_hook = "sed -i 's/_/-/g' ~/.config/rofi/colors.css"

[templates.vscode]
input_path = "templates/vscode.json"
output_path = "~/.vscode/extensions/hyprluna.hyprluna-matugen-theme-1.0.0/themes/hyprluna.json"

[templates.dunst]
input_path = 'templates/dunstrc'
output_path = '~/.config/dunst/dunstrc'
post_hook = "dunstctl reload"

[templates.Telegram]
input_path = "templates/telegram.theme"
output_path = "~/.config/telegram-desktop/themes/material-you.tdesktop-theme"