# : Manager [[[

[manager]
cwd = { fg = "#efe0d5" }

# Tab
tab_active = { fg = "#4c2700", bg = "#ffb779", bold = true }
tab_inactive = { fg = "#ffdcc1", bg = "#2e1500" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#bfcf64", bg = "#bfcf64" }
marker_cut = { fg = "#dfe7b2", bg = "#dfe7b2" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#c3cb97", bg = "#c3cb97" }

# Count
count_copied = { fg = "#181e00", bg = "#dfe7b2" }
count_cut = { fg = "#181e00", bg = "#dfe7b2" }
count_selected = { fg = "#4c2700", bg = "#c3cb97" }

# Border
border_symbol = "│"
border_style  = { fg = "#ffb779" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#4c2700", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#ffb779", fg = "#4c2700", bold = true }
normal_alt  = { bg = "#51443a", fg = "#d6c3b6" }

# Select mode
select_main = { bg = "#e3c0a5", fg = "#412c19", bold = true }
select_alt  = { bg = "#51443a", fg = "#d6c3b6" }

# Unset mode
unset_main = { bg = "#c3cb97", fg = "#2d330e", bold = true }
unset_alt  = { bg = "#51443a", fg = "#d6c3b6" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#ffb779", bg = "#413730" }
progress_error = { fg = "#ffb4ab", bg = "#413730" }

# Permissions
permissions_t = { fg = "#b66f39" }
permissions_w = { fg = "#7c8643" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#afc33d" }
permissions_s = { fg = "#ff8628" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#ffb779" }
active = { fg = "#c3cb97", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#ffb779" }
value = { fg = "#efe0d5" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#ffb779", bg = "#4c2700" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#ffb779" }
title = {}
hovered = { fg = "#dfe7b2", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#413730" }
cand = { fg = "#ffb779" }
rest = { fg = "#4c2700" }
desc = { fg = "#efe0d5" }
separator = " ▶ "
separator_style = { fg = "#efe0d5" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#efe0d5" }
run = { fg = "#efe0d5" }
footer = { fg = "#412c19", bg = "#e3c0a5" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#c3cb97" }
title_warn = { fg = "#ffb779" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#efe0d5" },
    { name = "*/", fg = "#ffb779" },
]

# : ]]]